// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"

	"go-wind-cms/app/book/service/internal/data"
	"go-wind-cms/app/book/service/internal/server"
	"go-wind-cms/app/book/service/internal/service"
)

func initApp(ctx *bootstrap.Context) (*kratos.App, func(), error) {
	entClient, cleanup, err := data.NewEntClient(ctx)
	if err != nil {
		return nil, nil, err
	}
	bookRepo := data.NewBookRepo(ctx.GetLogger(), entClient)
	bookService := service.NewBookService(ctx.GetLogger(), bookRepo)
	grpcServer, err := server.NewGrpcServer(ctx, bookService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(ctx, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
