oss:
  minio:
    endpoint: "192.168.31.203:9000"
    upload_host: "192.168.31.203:9000"
    download_host: "http://192.168.31.203:9000"
    access_key: "root"
    secret_key: "*Abcd123456"
    token: ""
    use_ssl: false