// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TradeOrdersColumns holds the columns for the "trade_orders" table.
	TradeOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "book_id", Type: field.TypeUint32},
		{Name: "book_title", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt32},
		{Name: "unit_price", Type: field.TypeFloat64, Default: 0},
		{Name: "total_price", Type: field.TypeFloat64, Default: 0},
		{Name: "user_id", Type: field.TypeUint32},
		{Name: "status", Type: field.TypeInt32, Default: 1},
	}
	// TradeOrdersTable holds the schema information for the "trade_orders" table.
	TradeOrdersTable = &schema.Table{
		Name:       "trade_orders",
		Columns:    TradeOrdersColumns,
		PrimaryKey: []*schema.Column{TradeOrdersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TradeOrdersTable,
	}
)

func init() {
	TradeOrdersTable.Annotation = &entsql.Annotation{
		Table: "trade_orders",
	}
}
