// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-cms/app/book/service/internal/data/ent/book"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   book.Table,
			Columns: book.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: book.FieldID,
			},
		},
		Type: "Book",
		Fields: map[string]*sqlgraph.FieldSpec{
			book.FieldCreatedAt: {Type: field.TypeTime, Column: book.FieldCreatedAt},
			book.FieldUpdatedAt: {Type: field.TypeTime, Column: book.FieldUpdatedAt},
			book.FieldDeletedAt: {Type: field.TypeTime, Column: book.FieldDeletedAt},
			book.FieldTitle:     {Type: field.TypeString, Column: book.FieldTitle},
			book.FieldAuthor:    {Type: field.TypeString, Column: book.FieldAuthor},
			book.FieldPrice:     {Type: field.TypeFloat64, Column: book.FieldPrice},
			book.FieldStock:     {Type: field.TypeInt32, Column: book.FieldStock},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *BookQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the BookQuery builder.
func (_q *BookQuery) Filter() *BookFilter {
	return &BookFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *BookMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the BookMutation builder.
func (m *BookMutation) Filter() *BookFilter {
	return &BookFilter{config: m.config, predicateAdder: m}
}

// BookFilter provides a generic filtering capability at runtime for BookQuery.
type BookFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *BookFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *BookFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(book.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *BookFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(book.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *BookFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(book.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *BookFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(book.FieldDeletedAt))
}

// WhereTitle applies the entql string predicate on the title field.
func (f *BookFilter) WhereTitle(p entql.StringP) {
	f.Where(p.Field(book.FieldTitle))
}

// WhereAuthor applies the entql string predicate on the author field.
func (f *BookFilter) WhereAuthor(p entql.StringP) {
	f.Where(p.Field(book.FieldAuthor))
}

// WherePrice applies the entql float64 predicate on the price field.
func (f *BookFilter) WherePrice(p entql.Float64P) {
	f.Where(p.Field(book.FieldPrice))
}

// WhereStock applies the entql int32 predicate on the stock field.
func (f *BookFilter) WhereStock(p entql.Int32P) {
	f.Where(p.Field(book.FieldStock))
}
