// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-cms/app/book/service/internal/data/ent/book"
	"go-wind-cms/app/book/service/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookMixin := schema.Book{}.Mixin()
	bookMixinFields0 := bookMixin[0].Fields()
	_ = bookMixinFields0
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[0].Descriptor()
	// book.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	book.TitleValidator = bookDescTitle.Validators[0].(func(string) error)
	// bookDescAuthor is the schema descriptor for author field.
	bookDescAuthor := bookFields[1].Descriptor()
	// book.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	book.AuthorValidator = bookDescAuthor.Validators[0].(func(string) error)
	// bookDescPrice is the schema descriptor for price field.
	bookDescPrice := bookFields[2].Descriptor()
	// book.DefaultPrice holds the default value on creation for the price field.
	book.DefaultPrice = bookDescPrice.Default.(float64)
	// bookDescStock is the schema descriptor for stock field.
	bookDescStock := bookFields[3].Descriptor()
	// book.DefaultStock holds the default value on creation for the stock field.
	book.DefaultStock = bookDescStock.Default.(int32)
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookMixinFields0[0].Descriptor()
	// book.IDValidator is a validator for the "id" field. It is called by the builders before save.
	book.IDValidator = bookDescID.Validators[0].(func(uint32) error)
}
