// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-cms/app/trade/service/internal/data/ent/order"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   order.Table,
			Columns: order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: order.FieldID,
			},
		},
		Type: "Order",
		Fields: map[string]*sqlgraph.FieldSpec{
			order.FieldCreatedAt:  {Type: field.TypeTime, Column: order.FieldCreatedAt},
			order.FieldUpdatedAt:  {Type: field.TypeTime, Column: order.FieldUpdatedAt},
			order.FieldDeletedAt:  {Type: field.TypeTime, Column: order.FieldDeletedAt},
			order.FieldBookID:     {Type: field.TypeUint32, Column: order.FieldBookID},
			order.FieldBookTitle:  {Type: field.TypeString, Column: order.FieldBookTitle},
			order.FieldQuantity:   {Type: field.TypeInt32, Column: order.FieldQuantity},
			order.FieldUnitPrice:  {Type: field.TypeFloat64, Column: order.FieldUnitPrice},
			order.FieldTotalPrice: {Type: field.TypeFloat64, Column: order.FieldTotalPrice},
			order.FieldUserID:     {Type: field.TypeUint32, Column: order.FieldUserID},
			order.FieldStatus:     {Type: field.TypeInt32, Column: order.FieldStatus},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *OrderQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OrderQuery builder.
func (_q *OrderQuery) Filter() *OrderFilter {
	return &OrderFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OrderMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OrderMutation builder.
func (m *OrderMutation) Filter() *OrderFilter {
	return &OrderFilter{config: m.config, predicateAdder: m}
}

// OrderFilter provides a generic filtering capability at runtime for OrderQuery.
type OrderFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OrderFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *OrderFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(order.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *OrderFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *OrderFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *OrderFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldDeletedAt))
}

// WhereBookID applies the entql uint32 predicate on the book_id field.
func (f *OrderFilter) WhereBookID(p entql.Uint32P) {
	f.Where(p.Field(order.FieldBookID))
}

// WhereBookTitle applies the entql string predicate on the book_title field.
func (f *OrderFilter) WhereBookTitle(p entql.StringP) {
	f.Where(p.Field(order.FieldBookTitle))
}

// WhereQuantity applies the entql int32 predicate on the quantity field.
func (f *OrderFilter) WhereQuantity(p entql.Int32P) {
	f.Where(p.Field(order.FieldQuantity))
}

// WhereUnitPrice applies the entql float64 predicate on the unit_price field.
func (f *OrderFilter) WhereUnitPrice(p entql.Float64P) {
	f.Where(p.Field(order.FieldUnitPrice))
}

// WhereTotalPrice applies the entql float64 predicate on the total_price field.
func (f *OrderFilter) WhereTotalPrice(p entql.Float64P) {
	f.Where(p.Field(order.FieldTotalPrice))
}

// WhereUserID applies the entql uint32 predicate on the user_id field.
func (f *OrderFilter) WhereUserID(p entql.Uint32P) {
	f.Where(p.Field(order.FieldUserID))
}

// WhereStatus applies the entql int32 predicate on the status field.
func (f *OrderFilter) WhereStatus(p entql.Int32P) {
	f.Where(p.Field(order.FieldStatus))
}
