// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/trade/service/internal/data/ent/order"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCreate) SetCreatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCreatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderCreate) SetUpdatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableUpdatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OrderCreate) SetDeletedAt(v time.Time) *OrderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableDeletedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetBookID sets the "book_id" field.
func (_c *OrderCreate) SetBookID(v uint32) *OrderCreate {
	_c.mutation.SetBookID(v)
	return _c
}

// SetBookTitle sets the "book_title" field.
func (_c *OrderCreate) SetBookTitle(v string) *OrderCreate {
	_c.mutation.SetBookTitle(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *OrderCreate) SetQuantity(v int32) *OrderCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *OrderCreate) SetUnitPrice(v float64) *OrderCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_c *OrderCreate) SetNillableUnitPrice(v *float64) *OrderCreate {
	if v != nil {
		_c.SetUnitPrice(*v)
	}
	return _c
}

// SetTotalPrice sets the "total_price" field.
func (_c *OrderCreate) SetTotalPrice(v float64) *OrderCreate {
	_c.mutation.SetTotalPrice(v)
	return _c
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_c *OrderCreate) SetNillableTotalPrice(v *float64) *OrderCreate {
	if v != nil {
		_c.SetTotalPrice(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrderCreate) SetUserID(v uint32) *OrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderCreate) SetStatus(v int32) *OrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableStatus(v *int32) *OrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrderCreate) SetID(v uint32) *OrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() {
	if _, ok := _c.mutation.UnitPrice(); !ok {
		v := order.DefaultUnitPrice
		_c.mutation.SetUnitPrice(v)
	}
	if _, ok := _c.mutation.TotalPrice(); !ok {
		v := order.DefaultTotalPrice
		_c.mutation.SetTotalPrice(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := order.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.BookID(); !ok {
		return &ValidationError{Name: "book_id", err: errors.New(`ent: missing required field "Order.book_id"`)}
	}
	if _, ok := _c.mutation.BookTitle(); !ok {
		return &ValidationError{Name: "book_title", err: errors.New(`ent: missing required field "Order.book_title"`)}
	}
	if v, ok := _c.mutation.BookTitle(); ok {
		if err := order.BookTitleValidator(v); err != nil {
			return &ValidationError{Name: "book_title", err: fmt.Errorf(`ent: validator failed for field "Order.book_title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Order.quantity"`)}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "Order.unit_price"`)}
	}
	if _, ok := _c.mutation.TotalPrice(); !ok {
		return &ValidationError{Name: "total_price", err: errors.New(`ent: missing required field "Order.total_price"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Order.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := order.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Order.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.BookID(); ok {
		_spec.SetField(order.FieldBookID, field.TypeUint32, value)
		_node.BookID = value
	}
	if value, ok := _c.mutation.BookTitle(); ok {
		_spec.SetField(order.FieldBookTitle, field.TypeString, value)
		_node.BookTitle = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeInt32, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(order.FieldUnitPrice, field.TypeFloat64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.TotalPrice(); ok {
		_spec.SetField(order.FieldTotalPrice, field.TypeFloat64, value)
		_node.TotalPrice = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(order.FieldUserID, field.TypeUint32, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreate) OnConflict(opts ...sql.ConflictOption) *OrderUpsertOne {
	_c.conflict = opts
	return &OrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreate) OnConflictColumns(columns ...string) *OrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertOne{
		create: _c,
	}
}

type (
	// OrderUpsertOne is the builder for "upsert"-ing
	//  one Order node.
	OrderUpsertOne struct {
		create *OrderCreate
	}

	// OrderUpsert is the "OnConflict" setter.
	OrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsert) SetUpdatedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUpdatedAt() *OrderUpsert {
	u.SetExcluded(order.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrderUpsert) ClearUpdatedAt() *OrderUpsert {
	u.SetNull(order.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsert) SetDeletedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateDeletedAt() *OrderUpsert {
	u.SetExcluded(order.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsert) ClearDeletedAt() *OrderUpsert {
	u.SetNull(order.FieldDeletedAt)
	return u
}

// SetBookID sets the "book_id" field.
func (u *OrderUpsert) SetBookID(v uint32) *OrderUpsert {
	u.Set(order.FieldBookID, v)
	return u
}

// UpdateBookID sets the "book_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateBookID() *OrderUpsert {
	u.SetExcluded(order.FieldBookID)
	return u
}

// AddBookID adds v to the "book_id" field.
func (u *OrderUpsert) AddBookID(v uint32) *OrderUpsert {
	u.Add(order.FieldBookID, v)
	return u
}

// SetBookTitle sets the "book_title" field.
func (u *OrderUpsert) SetBookTitle(v string) *OrderUpsert {
	u.Set(order.FieldBookTitle, v)
	return u
}

// UpdateBookTitle sets the "book_title" field to the value that was provided on create.
func (u *OrderUpsert) UpdateBookTitle() *OrderUpsert {
	u.SetExcluded(order.FieldBookTitle)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *OrderUpsert) SetQuantity(v int32) *OrderUpsert {
	u.Set(order.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *OrderUpsert) UpdateQuantity() *OrderUpsert {
	u.SetExcluded(order.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *OrderUpsert) AddQuantity(v int32) *OrderUpsert {
	u.Add(order.FieldQuantity, v)
	return u
}

// SetUnitPrice sets the "unit_price" field.
func (u *OrderUpsert) SetUnitPrice(v float64) *OrderUpsert {
	u.Set(order.FieldUnitPrice, v)
	return u
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUnitPrice() *OrderUpsert {
	u.SetExcluded(order.FieldUnitPrice)
	return u
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *OrderUpsert) AddUnitPrice(v float64) *OrderUpsert {
	u.Add(order.FieldUnitPrice, v)
	return u
}

// SetTotalPrice sets the "total_price" field.
func (u *OrderUpsert) SetTotalPrice(v float64) *OrderUpsert {
	u.Set(order.FieldTotalPrice, v)
	return u
}

// UpdateTotalPrice sets the "total_price" field to the value that was provided on create.
func (u *OrderUpsert) UpdateTotalPrice() *OrderUpsert {
	u.SetExcluded(order.FieldTotalPrice)
	return u
}

// AddTotalPrice adds v to the "total_price" field.
func (u *OrderUpsert) AddTotalPrice(v float64) *OrderUpsert {
	u.Add(order.FieldTotalPrice, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsert) SetUserID(v uint32) *OrderUpsert {
	u.Set(order.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUserID() *OrderUpsert {
	u.SetExcluded(order.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OrderUpsert) AddUserID(v uint32) *OrderUpsert {
	u.Add(order.FieldUserID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *OrderUpsert) SetStatus(v int32) *OrderUpsert {
	u.Set(order.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsert) UpdateStatus() *OrderUpsert {
	u.SetExcluded(order.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *OrderUpsert) AddStatus(v int32) *OrderUpsert {
	u.Add(order.FieldStatus, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(order.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrderUpsertOne) UpdateNewValues() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(order.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(order.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrderUpsertOne) Ignore() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertOne) DoNothing() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreate.OnConflict
// documentation for more info.
func (u *OrderUpsertOne) Update(set func(*OrderUpsert)) *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertOne) SetUpdatedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUpdatedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrderUpsertOne) ClearUpdatedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsertOne) SetDeletedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateDeletedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsertOne) ClearDeletedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetBookID sets the "book_id" field.
func (u *OrderUpsertOne) SetBookID(v uint32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetBookID(v)
	})
}

// AddBookID adds v to the "book_id" field.
func (u *OrderUpsertOne) AddBookID(v uint32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddBookID(v)
	})
}

// UpdateBookID sets the "book_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateBookID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateBookID()
	})
}

// SetBookTitle sets the "book_title" field.
func (u *OrderUpsertOne) SetBookTitle(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetBookTitle(v)
	})
}

// UpdateBookTitle sets the "book_title" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateBookTitle() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateBookTitle()
	})
}

// SetQuantity sets the "quantity" field.
func (u *OrderUpsertOne) SetQuantity(v int32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *OrderUpsertOne) AddQuantity(v int32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateQuantity() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *OrderUpsertOne) SetUnitPrice(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *OrderUpsertOne) AddUnitPrice(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUnitPrice() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetTotalPrice sets the "total_price" field.
func (u *OrderUpsertOne) SetTotalPrice(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetTotalPrice(v)
	})
}

// AddTotalPrice adds v to the "total_price" field.
func (u *OrderUpsertOne) AddTotalPrice(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddTotalPrice(v)
	})
}

// UpdateTotalPrice sets the "total_price" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateTotalPrice() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateTotalPrice()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsertOne) SetUserID(v uint32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OrderUpsertOne) AddUserID(v uint32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUserID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertOne) SetStatus(v int32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *OrderUpsertOne) AddStatus(v int32) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateStatus() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrderUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrderUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
	conflict []sql.ConflictOption
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrderUpsertBulk {
	_c.conflict = opts
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflictColumns(columns ...string) *OrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OrderUpsertBulk is the builder for "upsert"-ing
// a bulk of Order nodes.
type OrderUpsertBulk struct {
	create *OrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(order.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrderUpsertBulk) UpdateNewValues() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(order.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(order.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrderUpsertBulk) Ignore() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertBulk) DoNothing() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreateBulk.OnConflict
// documentation for more info.
func (u *OrderUpsertBulk) Update(set func(*OrderUpsert)) *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertBulk) SetUpdatedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUpdatedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrderUpsertBulk) ClearUpdatedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsertBulk) SetDeletedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateDeletedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsertBulk) ClearDeletedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetBookID sets the "book_id" field.
func (u *OrderUpsertBulk) SetBookID(v uint32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetBookID(v)
	})
}

// AddBookID adds v to the "book_id" field.
func (u *OrderUpsertBulk) AddBookID(v uint32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddBookID(v)
	})
}

// UpdateBookID sets the "book_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateBookID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateBookID()
	})
}

// SetBookTitle sets the "book_title" field.
func (u *OrderUpsertBulk) SetBookTitle(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetBookTitle(v)
	})
}

// UpdateBookTitle sets the "book_title" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateBookTitle() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateBookTitle()
	})
}

// SetQuantity sets the "quantity" field.
func (u *OrderUpsertBulk) SetQuantity(v int32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *OrderUpsertBulk) AddQuantity(v int32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateQuantity() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *OrderUpsertBulk) SetUnitPrice(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *OrderUpsertBulk) AddUnitPrice(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUnitPrice() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetTotalPrice sets the "total_price" field.
func (u *OrderUpsertBulk) SetTotalPrice(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetTotalPrice(v)
	})
}

// AddTotalPrice adds v to the "total_price" field.
func (u *OrderUpsertBulk) AddTotalPrice(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddTotalPrice(v)
	})
}

// UpdateTotalPrice sets the "total_price" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateTotalPrice() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateTotalPrice()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsertBulk) SetUserID(v uint32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OrderUpsertBulk) AddUserID(v uint32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUserID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserID()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertBulk) SetStatus(v int32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *OrderUpsertBulk) AddStatus(v int32) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateStatus() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
