// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/trade/service/internal/data/ent/order"
	"go-wind-cms/app/trade/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableUpdatedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *OrderUpdate) ClearUpdatedAt() *OrderUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrderUpdate) SetDeletedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDeletedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrderUpdate) ClearDeletedAt() *OrderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetBookID sets the "book_id" field.
func (_u *OrderUpdate) SetBookID(v uint32) *OrderUpdate {
	_u.mutation.ResetBookID()
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableBookID(v *uint32) *OrderUpdate {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// AddBookID adds value to the "book_id" field.
func (_u *OrderUpdate) AddBookID(v int32) *OrderUpdate {
	_u.mutation.AddBookID(v)
	return _u
}

// SetBookTitle sets the "book_title" field.
func (_u *OrderUpdate) SetBookTitle(v string) *OrderUpdate {
	_u.mutation.SetBookTitle(v)
	return _u
}

// SetNillableBookTitle sets the "book_title" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableBookTitle(v *string) *OrderUpdate {
	if v != nil {
		_u.SetBookTitle(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderUpdate) SetQuantity(v int32) *OrderUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableQuantity(v *int32) *OrderUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderUpdate) AddQuantity(v int32) *OrderUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *OrderUpdate) SetUnitPrice(v float64) *OrderUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableUnitPrice(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *OrderUpdate) AddUnitPrice(v float64) *OrderUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *OrderUpdate) SetTotalPrice(v float64) *OrderUpdate {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTotalPrice(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *OrderUpdate) AddTotalPrice(v float64) *OrderUpdate {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdate) SetUserID(v uint32) *OrderUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableUserID(v *uint32) *OrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrderUpdate) AddUserID(v int32) *OrderUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v int32) *OrderUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *int32) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OrderUpdate) AddStatus(v int32) *OrderUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.BookTitle(); ok {
		if err := order.BookTitleValidator(v); err != nil {
			return &ValidationError{Name: "book_title", err: fmt.Errorf(`ent: validator failed for field "Order.book_title": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(order.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(order.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(order.FieldBookID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBookID(); ok {
		_spec.AddField(order.FieldBookID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.BookTitle(); ok {
		_spec.SetField(order.FieldBookTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(order.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(order.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(order.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(order.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(order.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(order.FieldStatus, field.TypeInt32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableUpdatedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *OrderUpdateOne) ClearUpdatedAt() *OrderUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrderUpdateOne) SetDeletedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDeletedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrderUpdateOne) ClearDeletedAt() *OrderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetBookID sets the "book_id" field.
func (_u *OrderUpdateOne) SetBookID(v uint32) *OrderUpdateOne {
	_u.mutation.ResetBookID()
	_u.mutation.SetBookID(v)
	return _u
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableBookID(v *uint32) *OrderUpdateOne {
	if v != nil {
		_u.SetBookID(*v)
	}
	return _u
}

// AddBookID adds value to the "book_id" field.
func (_u *OrderUpdateOne) AddBookID(v int32) *OrderUpdateOne {
	_u.mutation.AddBookID(v)
	return _u
}

// SetBookTitle sets the "book_title" field.
func (_u *OrderUpdateOne) SetBookTitle(v string) *OrderUpdateOne {
	_u.mutation.SetBookTitle(v)
	return _u
}

// SetNillableBookTitle sets the "book_title" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableBookTitle(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetBookTitle(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderUpdateOne) SetQuantity(v int32) *OrderUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableQuantity(v *int32) *OrderUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderUpdateOne) AddQuantity(v int32) *OrderUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *OrderUpdateOne) SetUnitPrice(v float64) *OrderUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableUnitPrice(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *OrderUpdateOne) AddUnitPrice(v float64) *OrderUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetTotalPrice sets the "total_price" field.
func (_u *OrderUpdateOne) SetTotalPrice(v float64) *OrderUpdateOne {
	_u.mutation.ResetTotalPrice()
	_u.mutation.SetTotalPrice(v)
	return _u
}

// SetNillableTotalPrice sets the "total_price" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTotalPrice(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetTotalPrice(*v)
	}
	return _u
}

// AddTotalPrice adds value to the "total_price" field.
func (_u *OrderUpdateOne) AddTotalPrice(v float64) *OrderUpdateOne {
	_u.mutation.AddTotalPrice(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdateOne) SetUserID(v uint32) *OrderUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableUserID(v *uint32) *OrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrderUpdateOne) AddUserID(v int32) *OrderUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v int32) *OrderUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *int32) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OrderUpdateOne) AddStatus(v int32) *OrderUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.BookTitle(); ok {
		if err := order.BookTitleValidator(v); err != nil {
			return &ValidationError{Name: "book_title", err: fmt.Errorf(`ent: validator failed for field "Order.book_title": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(order.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(order.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BookID(); ok {
		_spec.SetField(order.FieldBookID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedBookID(); ok {
		_spec.AddField(order.FieldBookID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.BookTitle(); ok {
		_spec.SetField(order.FieldBookTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(order.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(order.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(order.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalPrice(); ok {
		_spec.SetField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalPrice(); ok {
		_spec.AddField(order.FieldTotalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(order.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(order.FieldUserID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(order.FieldStatus, field.TypeInt32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
