// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-cms/app/trade/service/internal/data/ent/order"
	"go-wind-cms/app/trade/service/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescBookTitle is the schema descriptor for book_title field.
	orderDescBookTitle := orderFields[1].Descriptor()
	// order.BookTitleValidator is a validator for the "book_title" field. It is called by the builders before save.
	order.BookTitleValidator = orderDescBookTitle.Validators[0].(func(string) error)
	// orderDescUnitPrice is the schema descriptor for unit_price field.
	orderDescUnitPrice := orderFields[3].Descriptor()
	// order.DefaultUnitPrice holds the default value on creation for the unit_price field.
	order.DefaultUnitPrice = orderDescUnitPrice.Default.(float64)
	// orderDescTotalPrice is the schema descriptor for total_price field.
	orderDescTotalPrice := orderFields[4].Descriptor()
	// order.DefaultTotalPrice holds the default value on creation for the total_price field.
	order.DefaultTotalPrice = orderDescTotalPrice.Default.(float64)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[6].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(int32)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderMixinFields0[0].Descriptor()
	// order.IDValidator is a validator for the "id" field. It is called by the builders before save.
	order.IDValidator = orderDescID.Validators[0].(func(uint32) error)
}
