// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"

	"go-wind-cms/app/trade/service/internal/data"
	"go-wind-cms/app/trade/service/internal/server"
	"go-wind-cms/app/trade/service/internal/service"
)

func initApp(ctx *bootstrap.Context) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(ctx)
	entClient, cleanup, err := data.NewEntClient(ctx)
	if err != nil {
		return nil, nil, err
	}
	bookClient := data.NewBookServiceClient(ctx, discovery)
	orderRepo := data.NewOrderRepo(ctx.GetLogger(), entClient)
	orderService := service.NewOrderService(ctx.GetLogger(), orderRepo, bookClient)
	grpcServer, err := server.NewGrpcServer(ctx, orderService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(ctx, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
